### ISSUE TITLE
Plugin build silently exits when it can't find build config

### ISSUE THREAD

**Issue by DarkFighterLuke** [oddstr13/jellyfin-plugin-repository-manager#174]
Hi, I am the developer of [TubeArchivistMetadata](https://github.com/tubearchivist/tubearchivist-jf-plugin) and your tool doesn't work when I build my project, neither on local machine nor in GitHub Actions.
It returns me an empty string as result after the build and it doesn't really output any artifact.

Apart from this, I find this tool very poor documented unfortunately...

**Comment by oddstr13** [comment]
Nothing silent about this error?

Logs are sent to stderr, not stdout, and exit code is appropriately returning `1`, indicating a failure (`0` == ok, everything else indicates error).

```
$ jprm plugin build
Setting project version to 1.2.3.0
Setting project framework to net6.0
MSBuild version 17.4.8+6918b863a for .NET
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
```

JPRM ran with debug logs shows the dotnet command;

```
$ jprm -v DEBUG plugin build 
debug: {'dotnet_config': 'Release', 'dotnet_framework': 'net6.0', 'output': '/tmp/tmp5ydb746i', 'max_cpu_count': 1, 'version': '1.2.3.0'}
Setting project version to 1.2.3.0
debug: Old version: 1.2.3.0
debug: Old file version: 1.2.3.0
debug: Old assembly version: 1.2.3.0
Setting project framework to net6.0
debug: ['run_os_command', ['dotnet', 'clean', '--configuration=Release', '--framework=net6.0'], None, False, '.']
MSBuild version 17.4.8+6918b863a for .NET
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
```

JPRM is self-documenting to a certain level, via the `--help` argument, try appending it to different commands.
Otherwise, all of Jellyfin's official plugins serve as practical examples.

**Comment by DarkFighterLuke** [comment]
Try to specify the project or solution then and you'll receive nothing in output in shell.
I tried to execute the plugin build both directly in the plugin source folder (Jellyfin.Plugin.TubeArchivistMetadata) and by specifying the folder to build. If you do in one of these ways, you will receive nothing as output and no artifacts as output.
![immagine](https://github.com/oddstr13/jellyfin-plugin-repository-manager/assets/31162436/99a142a9-ad71-446e-be14-07eeff7b1116)

**Comment by oddstr13** [comment]
Looks like it silently exits when it can't find the build config (`jprm.yaml` / `build.yaml`), that is unintentional.

**Comment by oddstr13** [comment]
I've merged a fix for the lack of errors there, but I've yet to publish a new release.

For now, you can assume that no output means it didn't find the config file in the path supplied.
https://github.com/oddstr13/jellyfin-plugin-repository-manager/blob/9497a0a499416cc572ed2e07a391d9f943a37b4d/jprm/__init__.py#L37-L45

**Comment by oddstr13** [comment]
Your project is missing a .sln file, which is why the dotnet clean command is erroring btw.
https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-sln#create-a-solution-file

**Comment by DarkFighterLuke** [comment]
My project is missing the .sln file, but it is only required for Visual Studio solutions, the main thing is the .csproj file, which is included in the plugin folder.

**Comment by oddstr13** [comment]
The dotnet clean command executed by jprm says otherwise.

**Comment by DarkFighterLuke** [comment]
I think I found the issue running with the debugger: the script searches build configuration files in the same specified folder https://github.com/oddstr13/jellyfin-plugin-repository-manager/blob/9497a0a499416cc572ed2e07a391d9f943a37b4d/jprm/__init__.py#L311-L315

The reason why it works with .sln file is that it is located outside the plugin source directory, while .csproj is inside that folder. If you specify the plugin source folder the script won't find the build configuration file, while if you specify the plugin project root folder the script will find the build configuration file but not the .csproj.

**Comment by joshuaboniface** [comment]
If that's the case, it would seem that your project is using a structure different than our official plugins or any third party plugins that we've seen use the JPRM tool before, though I haven't checked to confirm. I would suggest that you restore the original file layout from the template so that it matches our official plugins, as this is what JPRM is primarily built for. Any additional changes to support this would have to take into account effectively arbitrary plugin repository structures, and I'm not sure that's feasible at this time (though @oddstr13 may be able to confirm in the future if that'll be possible) without introducing too much complexity here.

That said, I agree that it probably shouldn't silently die, perhaps we could have a:

```
if build_cfg is None: 
    build_cfg = get_config(path) 

    if build_cfg is None: 
        print("ERROR: Could not find a valid JPRM metadata file.")
        print("Please see 'Metadata.md' in the JPRM repository for more details on how to configure a plugin for JPRM.")
        return None 
```

to print an error and reference `Metadata.md` instead.
