### ISSUE TITLE
[Question] regarding plugin checksum

### ISSUE THREAD

**Issue by h1dden-da3m0n** [oddstr13/jellyfin-plugin-repository-manager#5]
Any particular reason to use md5 checksum instead of secure sha256 or higher? (note I have briefly checked over the code, so might be an error on my sight of interpretation)

**Comment by crobibero** [comment]
This is what the server uses, theoretically we could support md5 for legacy, sha for new versions

**Comment by oddstr13** [comment]
I think that is mostly just due to Emby legacy?

This project started as a implementation of the existing repo format.

Raise a new issue if the Jellyfin server adds support for a different checksum type, and I'll implement it (or if it's decided that we will add support in the future, I can implement here first).
